### ISSUE TITLE
idempotent is not working

### ISSUE THREAD

**Issue by thorus90** [Nosmoht/ansible-module-powerdns#11]
My Playbook:
```
- powerdns_record:
    name: "{{ item.hostname | default(inventory_hostname) }}"
    zone: "{{ domain }}."
    type: "{{ powerdns.type }}"
    content: "{{ item.ip }}"
    ttl: "{{ powerdns.ttl }}"
    pdns_host: "{{ powerdns.host }}"
    pdns_port: "{{ powerdns.port }}"
    pdns_api_key: "{{ powerdns.api_key }}"
    pdns_prot: "{{ powerdns.prot }}"
    strict_ssl_checking: "{{ powerdns.strict_ssl_checking }}"
  with_items:
    - "{{ deployment.networks }}"
```
changed is always true, the dns record gets created and is present. Is there a switch I'm missing or sth?
