### ISSUE TITLE
SRV records

### ISSUE THREAD

**Issue by retr0h** [Nosmoht/ansible-module-powerdns#18]
I'm trying to add SRV records  with the module.  However, it appears the module will only add one record total. 

```
[jodewey:~/git/engx-ansible]   : DNACENGEX-2083-dns(+28/-28)+ ± dig _mysql._udp.dnac.xxx.com SRV

; <<>> DiG 9.10.6 <<>> _mysql._udp.dnac.xxx.com SRV
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 25306
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 2, ADDITIONAL: 3

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1280
;; QUESTION SECTION:
;_mysql._udp.dnac.xxx.com.        IN      SRV

;; ANSWER SECTION:
_mysql._udp.dnac.xxx.com. 300 IN  SRV     0 5 9104 dnac-dashboard-mysql-slave.dnac-dashboard-staging.svc.cluster.local.

;; AUTHORITY SECTION:
xxx

;; ADDITIONAL SECTION:
xxx

;; Query time: 48 msec
;; SERVER: 171.70.168.183#53(171.70.168.183)
;; WHEN: Wed Sep 18 18:17:06 PDT 2019
;; MSG SIZE  rcvd: 240

```

**Comment by blake** [comment]
@retr0h Can you share an example of the playbook & process you're using to create the SRV records?

I have a patch which allows adding multiple hostnames to MX records. It shouldn't take much to get it working for SRV records as well.

**Comment by blake** [comment]
@retr0h Can you share an example of the playbook & process you're using to create the SRV records? I'd like to clarify what the expected behavior is here.

Possibly related, I have a patch which enables `powerdns_record` to add multiple hostnames to a single MX record entry. Assuming the behavior I implemented there is what you're looking for, it shouldn't take much to get it working for SRV records as well.

**Comment by retr0h** [comment]
@blake 

The inventory:

```
pdns_svr_create:
  - name: _mysql._udp.dnac.xxx.com.
    zone: _udp.dnac.xxx.com
    type: SRV
    content: 0 5 9104 dnac-dashboard-mysql-slave.dnac-dashboard-production.svc.cluster.local.
    ttl: 300
  - name: _mysql._udp.dnac.xxx.com.
    zone: _udp.dnac.xxx.com
    type: SRV
    content: 0 5 9104 dnac-dashboard-mysql-slave.dnac-dashboard-staging.svc.cluster.local.
    ttl: 300
  - name: _mysql._udp.dnac.xxx.com.
    zone: _udp.dnac.xxx.com
    type: SRV
    content: 0 5 9104 dnac-dashboard-mysql-slave.dnac-dashboard-dev.svc.cluster.local.
    ttl: 300
  - name: _mysql._udp.dnac.xxx.com.
    zone: _udp.dnac.xxx.com
    type: SRV
    content: 0 5 9104 dnac-dashboard-mysql.dnac-dashboard-production.svc.cluster.local.
    ttl: 300
  - name: _mysql._udp.dnac.xxx.com.
    zone: _udp.dnac.xxx.com
    type: SRV
    content: 0 5 9104 dnac-dashboard-mysql.dnac-dashboard-staging.svc.cluster.local.
    ttl: 300
  - name: _mysql._udp.dnac.xxx.com.
    zone: _udp.dnac.xxx.com
    type: SRV
    content: 0 5 9104 dnac-dashboard-mysql.dnac-dashboard-dev.svc.cluster.local.
    ttl: 300
```

playbook

```
- hosts: dns-primary
  become: true
  tasks:
    - name: Create records
      powerdns_record:
        name: "{{ item.name }}"
        zone: "{{ item.zone }}"
        type: "{{ item.type }}"
        content: "{{ item.content }}"
        ttl: "{{ item.ttl }}"
        pdns_host: "{{ pdns_bind_address }}"
        pdns_port: "{{ pdns_api_port }}"
        pdns_api_key: "{{ pdns_api_password }}"
        state: "{{ item.state | default('present') }}"
      loop: "{{ pdns_hosts_create }}"
```

However, as reported in the original issue, only the last SRV record is ever added.
