### ISSUE TITLE
Feature: content as a list?

### ISSUE THREAD

**Issue by tabacha** [Nosmoht/ansible-module-powerdns#32]
Hi,
thank you for this module. 

I would like to suggest to mofiy the code so that content  can set a list.

The MX Example (from README.md) would then look like this:

```yaml
- powerdns_record:
    name: zone01.internal.example.com.
    zone: zone01.internal.example.com
    type: MX
    content: 
      - 10 mx1.zone01.internal.example.com
      - 10 mx2.zone01.internal.example.com
    pdns_host: powerdns.example.com
    pdns_port: 80
    pdns_api_key: topsecret
    pdns_prot: http
  loop:
```
And will even delete a wrong mx record if it was there before. Doing this from outside (without python with ansible and a dig look is not very fine, as you make sure the dig lookup will use the right resolver without caching.
